### ISSUE TITLE
Mine the coin?

### ISSUE THREAD

**Issue by Balt00** [bandexcoin-project/bandexcoin#1]
Hi, am i allowed to mine the coin? Since you've restarted the chain, looks like you didnt want people to mine it, or is that ok if i do mine?

**Comment by bandexcoin-project** [comment]
You can mine for sure the reason the coin was removed yesterday was that i changed coin maturity. make sure to remove all files from the old coin you have to uninstal it from control panel and go to folder C:\Users\user\AppData\Roaming and remove bandexcoin folder in here




Thx for using the coin :))

**Comment by Balt00** [comment]
Hi, okk thanks for answering, i didn't want to be intrusive and mine it while you didn't want.

You did good by changing coin maturity, the previous value of 10 was way too low and too risky for the chain, 100 is more secure considering the block time.

Is there a discord group yet perhaps where people could come chat?

Ty

**Comment by bandexcoin-project** [comment]
Thank you very much, yes i changed the block maturity cause i wanna be perfect :)

**Comment by bandexcoin-project** [comment]
i will soon create a Discord server :)
